---
 
- name: Exercise for setting up a web server in an EC 
  # hosts: ubuntu
  # Use the public IP if the VM is already created
  hosts: 44.203.100.112
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  roles:
  - setup
    