# update Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  myjob1:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo "hello world"

  configure_infrastructure:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["1d9:fa:a4:50:72:4b:e4:74:8e:37:85:a8:2e:98:94:9e"]
      - run:
          name: Install Ansible
          command: |
            python --version
            python -m pip install --user ansible

      - run:
          name: Run Playbook and Configure Server
          command: |
            ansible-playbook -i inventory main-remote.yml

workflows:
  my_workflow:
    jobs:
      - myjob1
      - configure_infrastructure
      #- welcome/run
      #- print_hello
      #- print_world:
      #   requires:
      #     - print_hello
